# Generated by Django 4.2.2 on 2023-06-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("human", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="human.subject",
                to_field="title",
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="list_answers",
            field=models.ManyToManyField(to="course.answer"),
        ),
        migrations.AddField(
            model_name="result",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="human.student",
                verbose_name="Student",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course.test",
                to_field="title",
                verbose_name="Test",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="course.test",
                to_field="title",
                verbose_name="Test",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="course.question",
                to_field="text",
                verbose_name="Question",
            ),
        ),
    ]
